const axios = require("axios");
const settings = require("../settings");
const small_lib = require("../lib/small_lib");

module.exports = async (sock, msg, from, body, args) => {
    const textQuery = args.join(" ").trim();

    if (!textQuery) {
        return sock.sendMessage(from, {
            text: `📝 *PDF Generator*\n\nConvert text, text file URLs (.txt), or image URLs (.png, .jpg, .jpeg, .webp, .gif) directly into a PDF payload.\n\n*Examples:*\n${settings.prefix}topdf Highly classified document generated by AI.\n${settings.prefix}topdf https://example.com/logo.png`
        }, { quoted: msg });
    }

    try {
        await sock.sendMessage(from, { react: { text: "🖨️", key: msg.key } }).catch(() => { });
        await sock.sendMessage(from, { text: "⌛ Generating Document…" }, { quoted: msg });

        // Hit PrinceTech API
        const url = `https://api.princetechn.com/api/tools/topdf?apikey=prince&query=${encodeURIComponent(textQuery)}`;

        const res = await axios.get(url, { responseType: "arraybuffer", timeout: 60000 });
        const pdfBuffer = Buffer.from(res.data);

        // Send back to WhatsApp as a Document
        await sock.sendMessage(from, {
            document: pdfBuffer,
            mimetype: "application/pdf",
            fileName: `${small_lib.botName} Document.pdf`,
            caption: `📄 Generated by ${small_lib.author}`
        }, { quoted: msg });

        await sock.sendMessage(from, { react: { text: "✅", key: msg.key } }).catch(() => { });

    } catch (e) {
        console.log("ToPDF Error:", e.response?.data?.toString() || e.message);
        await sock.sendMessage(from, { text: "❌ Failed to generate PDF." }, { quoted: msg });
        await sock.sendMessage(from, { react: { text: "⚠️", key: msg.key } }).catch(() => { });
    }
};
